### ISSUE TITLE
Why add translation by initializeWidget method?

### ISSUE THREAD

**Issue by baumannsven** [contao-community-alliance/contao-multicolumnwizard-bundle#105]
If column field, has the same name of not column field, then the label where overridden. Why is this the case? I think that is very bad.

https://github.com/menatwork/contao-multicolumnwizard-bundle/blob/e9594b1b2dbe3684100a8059fb2e99eed3ff2964/src/Contao/Widgets/MultiColumnWizard.php#L1160-L1162

**Comment by stefanheimes** [comment]
IF the field is not defined in the DCA then define it. Because we need the label for all the overlays and pickers.
