### ISSUE TITLE
PHP8 compatibility

### ISSUE THREAD

**Issue by jxns** [contao-community-alliance/contao-multicolumnwizard-bundle#113]
I am using the `contao-changelanguage` bundle which requires your `contao-multicolumnwizard-bundle`.
When trying to update, I receive the following error message:

`[1461.2MiB/9.16s] Your requirements could not be resolved to an installable set of packages. [1461.2MiB/9.16s] Problem 1 - terminal42/contao-changelanguage[3.2.0, ..., 3.2.1] require menatwork/contao-multicolumnwizard-bundle ^3.3 -> satisfiable by menatwork/contao-multicolumnwizard-bundle[3.4.0, ..., 3.4.11]. - menatwork/contao-multicolumnwizard-bundle[3.4.0, ..., 3.4.11] require php ^5.6 || ^7.0 -> your php version (8.0.9.0) does not satisfy that requirement. - Root composer.json requires terminal42/contao-changelanguage ^3.2 -> satisfiable by terminal42/contao-changelanguage[3.2.0, 3.2.1].`

Is PHP8 compatibility already in planning?

**Comment by zonky2** [comment]
>Is PHP8 compatibility already in planning?

Yes

**Comment by stefanheimes** [comment]
We allowed PHP 8 in version 3.4.12 and 3.5.1.
