### ISSUE TITLE
Adding a row results in page reload, if loaded in subpalette

### ISSUE THREAD

**Issue by ben-eSM** [contao-community-alliance/contao-multicolumnwizard-bundle#19]
The ajax function for adding new rows seems not to be getting initialized if the Multicolumnwizard is loaded in a subpalette. Therefore adding a row results in opening the add button's href, which will discard all changes done in other fields of the form.

**Comment by stefanheimes** [comment]
Okay i added something to prevent a reload after a js-error and i fix the subpalette error. 
In version 3.4.0-beta8 this problem should be fixed. Can you please test it @ben-eSM , thx.

**Comment by ben-eSM** [comment]
The fix is working as intended. Can't reproduce the issue now.

**Comment by zonky2** [comment]
thx
