### ISSUE TITLE
Adding a row results in 500 if the new item hasn't any valid id

### ISSUE THREAD

**Issue by stefanheimes** [contao-community-alliance/contao-multicolumnwizard-bundle#23]
If we create a new item and this item doesn't have an id, the AJAX callback returns a 500. I only see it on DCG and MetaModels.

**Comment by zonky2** [comment]
I can't confirm this!

**Comment by stefanheimes** [comment]
I have to test it  again.

**Comment by discordier** [comment]
I might have fixed this with fa61b811725b419f49c97b11163ce251d7707ae0. While this was not my original problem, it could have resulted from the same code.
