### ISSUE TITLE
pagePicker doesn´t work

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/contao-multicolumnwizard-bundle#26]
modal view show fileTree

![screenshot_366](https://user-images.githubusercontent.com/1045318/51260077-bfd5b080-19ad-11e9-8bbf-9a18e02e35a0.jpg)

```
            'mcw_pagetree' => array
                (
                'label'         => &$GLOBALS['TL_LANG'][$strTblName]['mcw_pagetree'],
                'exclude'       => true,
                'inputType'     => 'pageTree',
                'eval'          => array
                    (
                    'fieldType' => 'checkbox',
                    'multiple'  => true
                    )
                ),
```

**Comment by zonky2** [comment]
* 1st open modal: show page tree
* select page and submit => nothing happened...
* click the same button second one: modal show **file tree**
* select page and submit => file was taken over

**Comment by zonky2** [comment]
checked: works fine

**Comment by stefanheimes** [comment]
Done and part of version 3.4.0.
