### ISSUE TITLE
text with filePicker doesn´t works

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/contao-multicolumnwizard-bundle#27]
modal view show only folder

![screenshot_366](https://user-images.githubusercontent.com/1045318/51260406-7cc80d00-19ae-11e9-893b-7b5298ab0a02.jpg)

```
            'mcw_textfp' => array
                (
                'label'         => &$GLOBALS['TL_LANG'][$strTblName]['mcw_text'],
                'exclude'       => true,
                'inputType'     => 'text',
                'eval'          => array('style'=>'width:150px', 'decodeEntities'=>true, 'maxlength'=>255, 'fieldType'=>'radio', 'filesOnly'=>true,),
                'wizard'        => array(array('MultiColumnWizardHelper', 'mcwFilePicker'))
                ),
```

**Comment by stefanheimes** [comment]
Okay, the helper code seems to be not Contao 4 and i see that there is a new DCA Setting called dcaPicker.
Have to rework this part.

**Comment by stefanheimes** [comment]
I replace the old code with the new one. This should work now. But i recommend not to use the 'MultiColumnWizardHelper::mcwFilePicker' ever again. Use the ```dcaPicker``` settings from the DCA.

**Comment by zonky2** [comment]
We should add some informations at readme to change the versions...

**Comment by zonky2** [comment]
checked: works fine
