### ISSUE TITLE
text with pagePicker doesn´t works correct

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/contao-multicolumnwizard-bundle#28]
the modal view show more than pages - see screenshot

![screenshot_370](https://user-images.githubusercontent.com/1045318/51261089-e4cb2300-19af-11e9-97eb-7c8290073681.jpg)

```
            'mcw_textpp' => array
                (
                'label'         => &$GLOBALS['TL_LANG'][$strTblName]['mcw_text'],
                'exclude'       => true,
                'inputType'     => 'text',
                'eval'          => array('style'=>'width:150px','rgxp'=>'url', 'decodeEntities'=>true, 'maxlength'=>255, 'fieldType'=>'radio', 'filesOnly'=>true,),
                'wizard'        => array(array('tl_content', 'pagePicker'))
                ),


```

**Comment by stefanheimes** [comment]
The tabs are default by Contao. So i will do no change to this. Since this is Contao and not MCW.
But i will take a look at the "Untitled"

**Comment by zonky2** [comment]
* it´s not possible to hide or select the viewed tabs?
* if we see all tabs, the "News/Nachrichten" should also works

**Comment by zonky2** [comment]
... maybe we change from `pagePicker` to `contentPicker` ?

**Comment by zonky2** [comment]
`pagePicker`is deprecated https://github.com/contao/contao/blob/77f5076cdcda33c9fd56a1aa3f551398f59bd62b/core-bundle/src/Resources/contao/dca/tl_content.php#L1692

maybe we change automaticaly to `dcaPicker` ?

**Comment by stefanheimes** [comment]
I don't call it. It is part of Contao. So if contao makes the switch everything should be fine.

**Comment by stefanheimes** [comment]
Btw, correct the problem with the title.

**Comment by zonky2** [comment]
News works https://github.com/contao/core-bundle/issues/1679

**Comment by zonky2** [comment]
tested; works fine

**Comment by stefanheimes** [comment]
Done and part of version 3.4.0.
