### ISSUE TITLE
Min/Max - "Add"-Button is still visible

### ISSUE THREAD

**Issue by stefanheimes** [contao-community-alliance/contao-multicolumnwizard-bundle#3]
If we have a min/max level, the "Add"-Button is still visible. Tested in MetaModels - Attribute setting: 

![image](https://user-images.githubusercontent.com/988286/49887290-3e35b480-fe3c-11e8-874b-7491c827ae3e.png)

**Comment by stefanheimes** [comment]
Fixed in 9d25f0669d5c015c2684519c9e1e6f7ea6d6948e

**Comment by zonky2** [comment]
tested => o.k.
