### ISSUE TITLE
Colorpicker has image path errors

### ISSUE THREAD

**Issue by Total-Reality** [contao-community-alliance/contao-multicolumnwizard-bundle#34]
The images to display the colors reference to mootools... this is a wrong path (right side of the screen):
assets/mootools/colorpicker//images

Using the colorpicker directly in Contao 4 (left side of the screen) show me another path:
assets/colorpicker/images/

Installed versions:
Contao 4.4.31 
menatwork/contao-multicolumnwizard 3.3.16

![launcher 22 01 2019 135026](https://user-images.githubusercontent.com/5235894/51536943-7540b200-1e4d-11e9-9eb7-cb3990da0f8f.jpg)

**Comment by zonky2** [comment]
> Installed versions:
> Contao 4.4.31
> menatwork/contao-multicolumnwizard 3.3.16

you or your application should change to MCW-bundle

color picker works fine => https://github.com/menatwork/contao-multicolumnwizard-bundle/issues/25

**Comment by Total-Reality** [comment]
Hi,
ahh nice, thank you :)
It is correct that the filepicker problem is also fixed? This would be great.

**Comment by zonky2** [comment]
check issue #25 ...

**Comment by zonky2** [comment]
check your app and close the ticket
