### ISSUE TITLE
composer.json minimum php version incorrect

### ISSUE THREAD

**Issue by leeevin97** [contao-community-alliance/contao-multicolumnwizard-bundle#37]
https://github.com/menatwork/contao-multicolumnwizard-bundle/blob/ed1918165d8f809b596cf57bfc8b564f3de8625b/src/MultiColumnWizardBundle.php#L36

There's a incompatibility problem with the defined php version and the usage of the constant modifiers in the MultiColumnWizardBundle Class and maybe in some others. The minimum PHP version for these features are at least >= 7.1.0.

This should be fixed.

**Comment by stefanheimes** [comment]
See #38
