### ISSUE TITLE
The "maw.mcw.events.listener.load_data_container" service is private

### ISSUE THREAD

**Issue by discordier** [contao-community-alliance/contao-multicolumnwizard-bundle#4]
Loading a data container containing an MCW raises a deprecation notice:
`User Deprecated: The "maw.mcw.events.listener.load_data_container" service is private, checking for its existence is deprecated since Symfony 3.2 and will fail in 4.0.`

We should either make the service public (discouraged) or inject the service properly (encouraged).

**Comment by stefanheimes** [comment]
Since we need this for the contao hooks, i change them to ```public```. 
See fe97a84625d190980f0b0200b6ff039bc965ac6b

Maybe we can refactor this as well.

**Comment by zonky2** [comment]
I check it - I don´t see anymore
