### ISSUE TITLE
menatwork/contao-multicolumnwizard-bundle Fehler beim installieren

### ISSUE THREAD

**Issue by csaeum** [contao-community-alliance/contao-multicolumnwizard-bundle#41]
Wer hatte schonmal folgende Fehlermeldung beim installieren von menatwork/contao-multicolumnwizard-bundle

Ich hatte bisher das menatwork/contao-multicolumnwizard installiert muss aber durch ein anderes Plugin auf menatwork/contao-multicolumnwizard-bundle wechseln.

Bekomme aber nun diesen Fehler!

> @server:~/Contao4$ php-7.2-cli -d memory_limit=-1 composer.phar require menatwork/contao-multicolumnwizard-bundle
Using version ^3.4 for menatwork/contao-multicolumnwizard-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files
> ComponentInstaller\Installer:ostAutoloadDump
Compiling component files
contao/manager-plugin: Generating plugin class...
contao/manager-plugin: ...done generating plugin class
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
> Contao\ManagerBundle\Composer\ScriptHandler::initi alizeApplication

> In CheckExceptionOnInvalidReferenceBehaviorPass.php line 31:

> The service "MenAtWork\MultiColumnWizardBundle\EventListener\M cw\ColorPicke
r" has a dependency on a non-existent service "contao.translation.translato
r".

> Script Contao\ManagerBundle\Composer\ScriptHandler::initi alizeApplication handling the post-update-cmd event terminated with an exception

> [RuntimeException]
An error occurred while executing the "contao:install-web-dir" command:
In CheckExceptionOnInvalidReferenceBehaviorPass.php line 31:

> The service "MenAtWork\MultiColumnWizardBundle\EventListener\M cw\ColorPicke
r" has a dependency on a non-existent service "contao.translation.translato
r".

> require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

Im Forum wurde mir gesagt  ich sollte es hier auch mal posten:
https://community.contao.org/de/showthread.php?74196-menatwork-contao-multicolumnwizard-bundle-Fehler-beim-installieren&p=497639#post497639

**Comment by stefanheimes** [comment]
@csaeum Welche Contao Version benutzt ihr? Ich hatte mit meiner Contao 4.4 Version keine Probleme.

**Comment by stefanheimes** [comment]
Okay ich konnte es nachstellen mit einer neuen Installation. Ich werde es beheben.

**Comment by csaeum** [comment]
Oh sorry total vergessen:

C 4.4 Managed Edition aktuell.

Bei mir ist es dann gekommen als ich das Plugin "reluem/contao-uikit" installieren wollte.

**Comment by fritzmg** [comment]
Den translator gibt es erst ab Contao 4.5, iirc

**Comment by discordier** [comment]
@stefanheimes require den backported translator aus c-c-a.

**Comment by stefanheimes** [comment]
Should be fixed in version 3.4.1 

@csaeum can you please test it with the new version thanks.

**Comment by csaeum** [comment]
I am not a developer

can I install the "TestVersion" via Composer and then test it?

**Comment by discordier** [comment]
It has already been released, see: https://github.com/menatwork/contao-multicolumnwizard-bundle/releases/tag/3.4.1

Simply update via composer.

**Comment by csaeum** [comment]
Okay, I made an update on Composer this morning and my mistakes are gone and my Contao is running again.

thank you for your help

**Comment by stefanheimes** [comment]
You are welcome. Thanks for the ticket and the test.
