### ISSUE TITLE
bc break in GetOptionsEvent

### ISSUE THREAD

**Issue by discordier** [contao-community-alliance/contao-multicolumnwizard-bundle#5]
The old `MultiColumnWizard\Event\GetOptionsEvent` initialized the options as `null` and therefore provided a decision point if anyone already set the options (`null` => no one set anything, `[]` => someone decided the option list should be empty).

Now we check for:
```php
if (null !== $event->getOptions()) {
    return;
}
```
...and therefore get empty lists.

How shall we proceed here? Should we add a function `hasBeenSet()` to the event which returns `false` until the first `setOptions()` call?

This will still break existing listeners in the wild that use the "old" class, in fact, I only came to look after this as I saw the deprecation notice.

**Comment by stefanheimes** [comment]
See 603ce2d89ca56015b79127ec681757b7de8d78ca

**Comment by stefanheimes** [comment]
Released in 3.4.0-beta5
