### ISSUE TITLE
FormDependentMandatoryField and MultiColumnWizard

### ISSUE THREAD

**Issue by WebNetCrea** [contao-community-alliance/contao-multicolumnwizard-bundle#52]
Hello,

When i activate dependent mandatory form field, i have an error

Contao 4.7.6
cliffparnitzky/form-dependent-mandatory-field Version 2.1.2
menatwork/contao-multicolumnwizard-bundle Version 3.4.1

Argument 1 passed to FormDependentMandatoryField::getAllInputFormFields() must be an instance of MultiColumnWizard, instance of MenAtWork\MultiColumnWizardBundle\Contao\Widgets\MultiColumnWizard given, called in /home/clients/f033bee5d301812b2774c8b8edd6a14f/web/v3/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Widget.php on line 1316

**Comment by discordier** [comment]
Dupe of #39? Is fixed in `hotfix/3.4.2`. @stefanheimes will hopefully release soon...

**Comment by discordier** [comment]
3.4.2 is out of the door, closing therefore.
