### ISSUE TITLE
Fehler unter Contao 4.8 im Zusammenhang mit dem ContaoCommunityAlliance\Translator

### ISSUE THREAD

**Issue by Znrl** [contao-community-alliance/contao-multicolumnwizard-bundle#54]
Unter Contao 4.8 verursacht das Editieren/Erstellen von manchen Elementen z.B. dem Modul "Nachrichtenliste" einen Fehler.

z.B. https://community.contao.org/de/showthread.php?75742-Calendar_Extended-crasht-mit-Contao-4-8-0&p=509298#post509298

Vermutlich triggert der Event Listener "@contao.translation.translator"?
Es reicht einfach nur den Multicolumnwizard unter 4.8 zu installieren und ein Modul "Nachrichtenliste" zu erstellen.

**Comment by discordier** [comment]
See https://github.com/contao-community-alliance/translator/issues/8.
