### ISSUE TITLE
Change CSS Class invisible into hidden

### ISSUE THREAD

**Issue by stefanheimes** [contao-community-alliance/contao-multicolumnwizard-bundle#55]
We have to change the CSS class invisible  into hidden. Because invisible no longer works. The fields with the css class invisible are still visible.

**Comment by Aziz-JH** [comment]
What CSS class do you mean? If you need help I can help you with this bug.

**Comment by zonky2** [comment]
we must change `invisible` to `hidden`
https://github.com/menatwork/contao-multicolumnwizard-bundle/search?q=invisible&unscoped_q=invisible
