### ISSUE TITLE
Copy Button: copy.gif fehlt bei Initialisierung?

### ISSUE THREAD

**Issue by theDyingMountain** [contao-community-alliance/contao-multicolumnwizard-bundle#76]
Bei der Initialisierung des Button Arrays fehlt die Verknüpfung des copy.gif Images. Hat das einen Grund? [Siehe hier](https://github.com/menatwork/contao-multicolumnwizard-bundle/blob/master/src/Contao/Widgets/MultiColumnWizard.php#L150-L154)

```diff
protected $arrButtons = [
        'new'    => 'new.gif',
        'delete' => 'delete.gif',
        'move'   => 'drag.gif',
+        'copy'   => 'copy.gif'
    ];

**Comment by zonky2** [comment]
ja, hat einen Grund: ist noch nicht implementiert...
https://github.com/menatwork/contao-multicolumnwizard-bundle/issues/18
