### ISSUE TITLE
Anzahl der Zeilen vorgeben

### ISSUE THREAD

**Issue by EnricoSchiller** [contao-community-alliance/contao-multicolumnwizard-bundle#78]
Hallo! Gibt es eine Option mit der man, wie bei der Liste vom rocksolid costum elements, die Anzahl der Zeilen eingrenzen oder vorgeben kann? Beide Optionen wären sehr nützlich.

Danke!

**Comment by EnricoSchiller** [comment]
Gut einmal in den Code geguckt sieht man die Option:
`
case 'minCount':
case 'maxCount':
`
Aber vielleicht wäre es gut die Optionen die zur Verfügung stehen ins Markdown zu schreiben?

**Comment by zonky2** [comment]
ein Blick in die readme hätte wohl gereicht und dem Link http://de.contaowiki.org/MultiColumnWizard gefolgt...
