### ISSUE TITLE
GetOptionsEvent

### ISSUE THREAD

**Issue by stefanheimes** [contao-community-alliance/contao-multicolumnwizard-bundle#8]
We should trigger the new event instead of the old. 
Instead we should add a new listener, which trigger the old one.
And we should rename the new event name.

**Comment by stefanheimes** [comment]
See fe97a84625d190980f0b0200b6ff039bc965ac6b

**Comment by discordier** [comment]
See remark in fe97a84625d190980f0b0200b6ff039bc965ac6b
