### ISSUE TITLE
Text fields stay empty with multiple select

### ISSUE THREAD

**Issue by laufhannes** [contao-community-alliance/contao-multicolumnwizard-bundle#80]
I'm using the multi column wizard with text fields, checkboxes and a select (with `multiple=true`). But as soon as I allow multiple fields for the select menu, text fields won't be saved (they stay empty; the same applies for single-value selects via foreignKey). The multi select (and checkboxes) are handled correctly.

Example dca:

```php
$GLOBALS['TL_DCA']['tl_my_table']['fields']['my_multi_field'] = array
(
  'exclude' => true,
  'inputType' => 'multiColumnWizard',
  'eval' => array(
    'mandatory'=> true,
    'columnFields' => array(
      'multi_time' => array(
        'inputType' => 'text',
        'default' => '10:00',
        'eval' => array('maxlength' => '5', 'style' => 'width:50px;'),
      ),
      'multi_ak' => array(
        'inputType' => 'select',
        'multiple' => true,
        'options' => array('A', 'B', 'C'),
        'eval' => array('multiple' => true, 'size' => 6),
      )
    )
  ),
);
```

Any value entered for `multi_time` will be lost after saving.

Contao 4.8.8, PHP 7.1.33, MCW 3.4.4, only a few other extensions (Gallery Creator Bundle, psi/boxes4ward, + custom modules that should not affect MCW here).

**Comment by zonky2** [comment]
Hi @laufhannes its possible to you to send a fix as PR?

**Comment by laufhannes** [comment]
I did not manage to fix this when opening the issue.

Now I've found https://community.contao.org/de/showthread.php?66727-multiColumnWizard-mit-multiple-select&p=440426&viewfull=1#post440426 which helps me - I guess that has to be solved in the Core Bundle.

**Comment by zonky2** [comment]
fixed in https://github.com/menatwork/contao-multicolumnwizard-bundle/pull/87

but see https://github.com/contao/contao/issues/2271
