### ISSUE TITLE
Meta Models Filetree bei Multi-Column-Wizard

### ISSUE THREAD

**Issue by btosh82** [contao-community-alliance/contao-multicolumnwizard-bundle#91]
Hallo,

bei der Erstellung eines Custom Multi-Column-Elements mit Meta Models bleibt die Ausgabe im Backend leer.

Contao Version 4.4.54
Multi-Column-Wizard 3.4.7
metamodels/attribute_tablemulti Version 2.1.2

Meine Config:

```php
<?php

$GLOBALS['TL_CONFIG']['metamodelsattribute_multi']['mm_vehicle']['mc_vehicle_plans'] = array(
    'tl_class'     => 'clr',
    'minCount'     => 0,
    'maxCount'     => 20,
    'columnFields' => array(        
        'col_image' => array(
            'label'     => 'Grundriss',
            'exclude'   => true,
            'inputType' => 'fileTree',
            'eval'      => array
            (
                'fieldType'=>'radio', 
                'files'=>true, 
                'filesOnly'=>true, 
                'extensions'=>\Contao\Config::get('validImageTypes'),
                'mandatory' => true,
            ),
            'sql'		=> 'blob NULL'
        ),        
        'col_caption' => array(
            'label'     => 'Bildunterschrift',
            'exclude'   => true,
            'inputType' => 'text',
            'eval'      => array
            (
                'style'=>'width:300px',
                'maxlength'=>100, 
            )
        ),
    ),
);
``` 

Vielen Dank.

**Comment by zonky2** [comment]
zur Sicherheit das Ganze mit meinem Testcase in C4.4 und C4.9 eingebaut - kann keinen Fehler finden https://easycaptures.com/fs/uploaded/1511/7777882822.png

![7777882822](https://user-images.githubusercontent.com/1045318/98540698-9f679c00-228e-11eb-9d8f-457525fb055f.png)


Link zum Forum: https://community.contao.org/de/showthread.php?79337-Meta-Models-Filetree-bei-Multi-Column-Wizard&p=534596#post534596

**Comment by discordier** [comment]
@zonky2 Bitte screenshots direkt in github per copy&paste in den Kommentar packen... dein easycaptures tut immer mal wieder nicht (hier kommt sogar ein 404), dann haben wir die Infos persistent beisammen.

**Comment by zonky2** [comment]
easycapture geht schon, wenn man den Link richtig setzt und nicht aus dem Forum kopiert ;-)

**Comment by discordier** [comment]
Bekomme immer noch einen 404...

**Comment by zonky2** [comment]
ich nicht - habs eingefügt...

**Comment by zonky2** [comment]
fixed with https://github.com/menatwork/contao-multicolumnwizard-bundle/pull/92
